# Generated by Django 4.2.6 on 2024-01-28 15:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=20)),
                ('discount_value', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Coupon Discount',
                'verbose_name_plural': 'Coupon Discounts',
            },
        ),
        migrations.CreateModel(
            name='SeasonalDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('every_value', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_value', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Seasonal Discount',
                'verbose_name_plural': 'Seasonal Discounts',
            },
        ),
        migrations.CreateModel(
            name='OnTopDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('product_category', 'Product Category'), ('points', 'Points')], max_length=20)),
                ('discount_value', models.FloatField(default=0, help_text='Enter value in percentage eg. 50 for 50%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_manager.productcategory')),
            ],
            options={
                'verbose_name': 'On Top Discount',
                'verbose_name_plural': 'On Top Discounts',
            },
        ),
    ]
